import type { ThreatReport } from '../types/threat';

/** Trigger a JSON download of the full report. */
export function exportJson(report: ThreatReport): void {
  const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
  _download(blob, `threat-report-${slugify(report.target_url)}.json`);
}

/** Trigger an HTML download of the full report as a self-contained printable page. */
export function exportHtml(report: ThreatReport): void {
  const html = buildHtml(report);
  const blob = new Blob([html], { type: 'text/html' });
  _download(blob, `threat-report-${slugify(report.target_url)}.html`);
}

function _download(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function slugify(url: string): string {
  return url.replace(/https?:\/\//, '').replace(/[^a-zA-Z0-9]/g, '-').slice(0, 60);
}

function scoreColor(score: number): string {
  if (score >= 70) return '#ef4444';
  if (score >= 35) return '#eab308';
  return '#22c55e';
}

function checkRow(label: string, passed: boolean, detail: string): string {
  return `
    <tr>
      <td style="padding:8px 12px;border-bottom:1px solid #1f2937;">${passed ? '✅' : '❌'} <strong>${label}</strong></td>
      <td style="padding:8px 12px;border-bottom:1px solid #1f2937;color:#9ca3af;">${detail}</td>
    </tr>`;
}

function buildHtml(r: ThreatReport): string {
  const { checks } = r;
  const color = scoreColor(r.threat_score);
  const ts = new Date(r.timestamp).toLocaleString();

  const heuristicFlags = checks.url_heuristics.flags.length > 0
    ? `<ul style="margin:4px 0 0 16px;padding:0;color:#9ca3af;font-size:13px;">${checks.url_heuristics.flags.map(f => `<li>${f}</li>`).join('')}</ul>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Threat Report — ${r.target_url}</title>
  <style>
    body { font-family: system-ui, sans-serif; background: #030712; color: #f9fafb; margin: 0; padding: 32px; }
    h1 { font-size: 1.5rem; margin-bottom: 4px; }
    .url { color: #60a5fa; word-break: break-all; font-size: 0.9rem; }
    .score { font-size: 3rem; font-weight: 900; color: ${color}; }
    .meta { color: #6b7280; font-size: 0.8rem; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 24px; background: #111827; border-radius: 10px; overflow: hidden; }
    th { text-align: left; padding: 10px 12px; background: #1f2937; color: #6b7280; font-size: 0.75rem; text-transform: uppercase; letter-spacing: .05em; }
    td { vertical-align: top; }
    .footer { margin-top: 32px; color: #374151; font-size: 0.75rem; }
  </style>
</head>
<body>
  <h1>🔍 ThreatIntelD Report</h1>
  <div class="url"><a href="${r.target_url}" style="color:#60a5fa;">${r.target_url}</a></div>
  <div class="meta">Analyzed at ${ts} &mdash; Assessment: <strong style="color:${color}">${r.assessment}</strong></div>
  <div class="score">${r.threat_score}<span style="font-size:1.2rem;font-weight:400;color:#6b7280;">/100</span></div>
  <table>
    <thead><tr><th>Check</th><th>Details</th></tr></thead>
    <tbody>
      ${checkRow('Google Safe Browsing', !checks.safe_browsing.flagged, checks.safe_browsing.details)}
      ${checkRow('Domain Age', checks.domain_age.risk_level === 'Low', checks.domain_age.details)}
      ${checkRow('SSL Certificate', checks.ssl_certificate.valid, checks.ssl_certificate.details)}
      ${checkRow('VirusTotal', !checks.virustotal.detected, checks.virustotal.details)}
      ${checkRow('IP Reputation', !checks.ip_reputation.is_flagged, checks.ip_reputation.details)}
      ${checkRow('URL Heuristics', !checks.url_heuristics.is_suspicious, checks.url_heuristics.details)}
    </tbody>
  </table>
  ${heuristicFlags}
  <div class="footer">Generated by ThreatIntelD &mdash; ${ts}</div>
</body>
</html>`;
}
